Pixel 구조체와 Object 클래스 구현
KMU07/snake_game pull request #5
Opened 2023-05-26 13:25 UTC by longZam

## Pull Request 유형

- [ ] 버그 수정
- [X] 기능 추가
- [ ] 코드 스타일 업데이트
- [ ] 리팩토링 (기능 변경 없음, API 변경 없음)
- [ ] 문서 내용 변경
- [ ] 기타 사항: >>이 글을 지우고 새로 입력<<

## 요약

Object 클래스를 구현하였음.
Renderer.h 헤더 파일이 아직 존재하지 않아 include 하지는 않았음.

## 변경 사항 설명

추가된 파일
* Object.h, Object.cpp
* Pixel.h, Pixel.cpp

2023-05-26 14:43 UTC, yubincho3 requested changes
Pixel.cpp 파일은 삭제 부탁드립니다!

2023-05-26 14:43 UTC, yubincho3 commented on src/Pixel.cpp
딱히 필요 없는 파일이기도 하고, 추후에 기능을 확장하더라도 그 때는 Pixel 대신 새로운 class를 사용하는 편이 좋을 것 같기에 혼동을 막기 위해 삭제해놓는것이 좋을 것 같습니다.

2023-05-26 14:45 UTC, longZam commented on src/Pixel.cpp
그러면 deque<Pixel>도 제거하라는 뜻인가요?

2023-05-27 02:34 UTC, longZam commented on src/Pixel.cpp
수정했습니다. renderer는 레퍼런스로 두니 이니셜라이저가 꼭 필요하더라고요. 일단 받아올 방법이 없어서 공란으로 두었습니다.

2023-05-27 08:01 UTC, yubincho3 approved these changes
확인했습니다

2023-05-29 08:54 UTC, shinkihyeon approved these changes
코드 확인했습니다!

2023-05-29 08:54 UTC, merged