Renderer와 Game 클래스 추가, 코드 간략화, 버그 수정
KMU07/snake_game pull request #6
Opened 2023-05-29 15:51 UTC by yubincho3

## Pull Request 유형

- [x] 버그 수정
- [x] 기능 추가
- [x] 코드 스타일 업데이트
- [ ] 리팩토링 (기능 변경 없음, API 변경 없음)
- [ ] 문서 내용 변경
- [ ] 기타 사항: >>이 글을 지우고 새로 입력<<

## 요약

Object 클래스의 소멸자의 코드가 호출되지 않을 수 있던 문제를 virtual 소멸자로의 변경으로써 해결하였음.  

Object 클래스의 생성자와 소멸자의 Renderer 등록/해제 코드를 주석 해제하였음.  

Renderer, Game 클래스를 추가하였음.  

Pixel.h의 헤더 파일 include를 간소화 하였음.

## 변경 사항 설명

UML 만들때 Object 클래스의 소멸자를 virtual로 하는것을 미처 생각하지 못했습니다.  
다행히도 방금 발견하여 코드와 UML의 내용을 수정하였습니다.  

Game.h에 일정 시간마다 호출되는 invoke 함수들을 효율적으로 처리하기 위해 InvokeManager 클래스를 추가했습니다.  
UML에도 곧 추가할 예정이고, 주석이나 설명이 필요한 부분이 있으시면 comment 부탁드립니다.  

수정된 파일
* Pixel.h
* Object.h, Object.cpp

추가된 파일
* Renderer.h, Renderer.cpp
* Game.h, Game.cpp

2023-05-30 08:08 UTC, longZam requested changes

2023-05-30 08:09 UTC, longZam requested changes

2023-05-30 08:09 UTC, longZam commented on include/Game.h
> +    void invokeRepeat(Callback callback, Delay interval);
Delay 입력 단위가 s, ms, us 중 어떤 것인지 잘 모르겠습니다. 주석에 단위를 표시해주세요.

2023-05-30 08:16 UTC, yubincho3 commented on include/Object.h
> +    // 일정 시간마다 주기적으로 호출되는 함수
일단은 그냥 주석을 위에 달아놔도 함수 설명이 뜨길래 간략하게 해봤는데 제가 모르는 다른 기능이 있었나 보네요. 피곤한 상태에서 정리하다 보니 미처 확인을 못했네요 죄송합니다.

2023-05-30 08:17 UTC, longZam commented on include/Object.h
> +    // 일정 시간마다 주기적으로 호출되는 함수
두 줄로 해도 설명이 뜨나요? 제 IDE에서는 summary 없이는 표시가 안되더라고요.

2023-05-30 08:18 UTC, yubincho3 commented on include/Game.h
> +    void invokeRepeat(Callback callback, Delay interval);
일단 마이크로초까지는 한 자료형으로 사용할 수 있게 해보았는데, 확실히 단위를 통일해서 타입을 표시하는게 좋을 것 같네요!

2023-05-30 08:19 UTC, yubincho3 commented on include/Object.h
> +    // 일정 시간마다 주기적으로 호출되는 함수
앗 확인했습니다!

2023-05-31 05:13 UTC, yubincho3 commented on include/Game.h
> +    void invokeRepeat(Callback callback, Delay interval);
수정했습니다

2023-05-31 05:15 UTC, yubincho3 commented
Game.cpp에서 정의된 void InvokeManager::checkAndInvoke()의 코드 중, invoked callback들을 지우는 과정에서 하나의 invoke를 더 지우던 문제를 발견하여 수정했습니다.

2023-05-31 05:40 UTC, yubincho3 commented
다른 버그와 수정 해야 할 부분들이 발견되어 수정 중입니다.

2023-05-31 05:54 UTC, yubincho3 commented
게임이 start를 호출 후 충돌을 처리하고 나서 렌더링 하도록 하고, 게임 루프 중간에는 break 되지 않도록 변경했습니다.
또, InvokeManager::checkAndInvoke()에서 일정 시간마다 반복되어야 하는 invoke들을 다시 추가할 때, addInvoke 함수로 nextInvokeTime이 아니라 prevInvokeTime를 인자로 했던 문제를 수정했습니다.

2023-05-31 06:01 UTC, longZam approved these changes
LGTM

2023-05-31 10:40 UTC, shinkihyeon approved these changes
코드 확인했습니다!

2023-05-31 10:48 UTC, merged